---
server:
  port: 8080

samplepong:
  ribbon:
    DeploymentContextBasedVipAddresses: sample-inventory
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ReadTimeout: 5000
    MaxAutoRetries: 2


another:
  key: anotherkeyvalue
